# Домашнее задание "Линейная алгебра. Матрицы".

## Уровень 0:


### Задание 1

 - Создайте матрицу 3 на 3, заполненную числами от 1 до 9
 - Прибавьте к ней матрицу с единицами на диагонале
 - Умножьте полученную матрицу на вектор (1, 2, 3)
 - Вычислить транспонированную матрицу $A^T$ от полученной в результате прибавления матрицы
 - Посчитайте обратную матрицу к полученной в результате прибавления матрице


In [37]:
import numpy as np

A1=np.array([[1,3,6],[9,4,8],[7,2,5]])
A2=np.eye(3)
print('Сумма матриц:')
print(A1+A2,'\n')
print('Умножение матрицы на вектор:')
print((A1+A2)@[1,2,3],'\n')
print('Транспонированная матрица')
print(np.transpose(A1+A2),'\n')
print('Обратная матрица')
print(np.linalg.inv(A1+A2),'\n')
#проверка обратной матрицы
(A1+A2)@(np.linalg.inv(A1+A2))

Сумма матриц:
[[2. 3. 6.]
 [9. 5. 8.]
 [7. 2. 6.]] 

Умножение матрицы на вектор:
[26. 43. 29.] 

Транспонированная матрица
[[2. 9. 7.]
 [3. 5. 2.]
 [6. 8. 6.]] 

Обратная матрица
[[-0.20588235  0.08823529  0.08823529]
 [-0.02941176  0.44117647 -0.55882353]
 [ 0.25       -0.25        0.25      ]] 



array([[ 1.00000000e+00,  1.66533454e-16,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [-3.33066907e-16,  1.66533454e-16,  1.00000000e+00]])

## Уровень 1:

### Задание 2

Найдите собственные значения и собственные вектора матрицы:
```
m = np.array([[2, 2],
              [1, 3]])
print(m)
```



In [30]:
m = np.array([[2, 2],
              [1, 3]])
print('Собственные значения матрицы:')
print(np.linalg.eigvals(m),'\n')
print('Собственные векторы матрицы:')
np.linalg.eig(m)

Собственные значения матрицы:
[1. 4.] 

Собственные векторы матрицы:


(array([1., 4.]),
 array([[-0.89442719, -0.70710678],
        [ 0.4472136 , -0.70710678]]))

### Задание 3


Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2! 

In [34]:
np.linalg.det(np.array([[2,1],[5,3]]))

1.0000000000000002